# Generated by Django 3.2.7 on 2021-10-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwardingBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FundingYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("year_code", models.CharField(max_length=7)),
                ("description", models.CharField(max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("qualification_code", models.CharField(max_length=20)),
                ("qualification_title", models.CharField(max_length=200)),
                ("qualification_type2", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("num_credits", models.PositiveIntegerField(default=0)),
                ("is_part_of_apprenticeship", models.BooleanField(default=False)),
                ("is_pre_funded", models.BooleanField(default=False)),
                ("is_endpoint_assesement", models.BooleanField(default=False)),
                (
                    "level_for_endpoint_assesement",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("is_local_authority", models.BooleanField(default=False)),
                ("qualification_category", models.CharField(max_length=100)),
                ("qualification_type1", models.CharField(blank=True, max_length=100)),
                (
                    "awarding_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qualifications.awardingbody",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QualificationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("funding_value", models.PositiveIntegerField(default=0)),
                (
                    "funding_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qualifications.fundingyear",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qualifications.qualification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
