# Generated by Django 3.2.7 on 2021-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("workplace", models.CharField(max_length=255)),
                ("job_role", models.CharField(max_length=255)),
            ],
        ),
    ]
